### ISSUE TITLE
Update Airtable with challenges

### ISSUE THREAD

**Issue by hack4cause** [Hack4Eugene/hack-4-cause-2019-plan#10]
read-only link to [airtable](https://airtable.com/invite/l?inviteId=inviLIdrtt72RnYtB&inviteToken=6ad12622b4539a55702ae83d4e05c8e4def7e2c71d0f96ad53858ababe3afc78)

- [ ] find the editable link in the **#tech-mentors** channel in the [Slack](http://hack4cause.slack.com)
- [ ] find the challenges listed on the [web-site](https://hackforacause.org/challenges-2019/)
- [ ] update the airtable base with challenges

**Comment by markdav-is** [comment]
I did all of them exept for Lane County

oregon-campaign-trail
hiv-alliance-sheltercare
oregon-family-support-net
homeless-resource-finder
community-enguagement-tools
urban-pong
carry-it-forward

**Comment by markdav-is** [comment]
done
