### ISSUE TITLE
propose name change to tech-volunteer for 2020

### ISSUE THREAD

**Issue by markdav-is** [Hack4Eugene/hack-4-cause-2019-plan#21]
its confusing that we call everyone tech mentors when they sign up and then have multiple flavors: judge, av-geek, etc.  we could change that to tech-volunteer at signup?

**Comment by mattsayre** [comment]
Agree on the value of streamlining. Eventbrite reflects this now (as of 4/7/2019). Then volunteers self select into roles and time slots on the volunteer sheet. There is a column in that sheet for "on slack", but no request for phone number and no email addresses are published.

**Comment by markdav-is** [comment]
looks like this is allready happening, so we can close this.
