### ISSUE TITLE
public slack inviter for hack4cause slack?

### ISSUE THREAD

**Issue by markdav-is** [Hack4Eugene/hack-4-cause-2019-plan#22]
@mattsayre  would you like to have a public slack inviter for the hack4cause slack so we can bypass the EugeneTech slack to get folks invited to the slack?

**Comment by mattsayre** [comment]
If we can make the event more accessible, that seems like a good thing, including slack.

**Comment by markdav-is** [comment]
here ya go:  https://publicslack.com/slacks/hack4cause/invites/new
