### ISSUE TITLE
Create challenge channels

### ISSUE THREAD

**Issue by markdav-is** [Hack4Eugene/hack-4-cause-2019-plan#5]
- [ ] look for challenges in #challenges 
- [ ] create new challenge using the format c-[challenge-name]
- [ ] copy challenge doc to challenge channel
- [ ] invite challenge owner to channel

**Comment by hack4cause** [comment]
list of challenges posted: https://hackforacause.org/challenges-2019/

**Comment by markdav-is** [comment]
these are done
